### ISSUE TITLE
на wind 10

### ISSUE THREAD

**Issue by Chif115** [Noname400/HtM-Lite#3]
Во-первых, Спасибо за работу!
Не запускается bloom-create.py на wind 10. Пишет:
"ice.scalar_multiplication.argtypes = [ctypes.c_char_p, ctypes.c_char_p]   # pvk,ret
NameError: name 'ice' is not defined".

Во-вторых вопрос: что-нибудь удалось найти?

**Comment by Noname400** [comment]
Виндовс 10 x64?
Проверьте наличие файла dll

**Comment by DFKTYNBY967** [comment]
ice_secp256k1.dll    --- ЭТОТ ФАЙЛ ВЫ ИМЕЕТЕ В ВИДУ?
