### ISSUE TITLE
Не получается запустить

### ISSUE THREAD

**Issue by 5k1n** [Noname400/HtM-Lite#4]
Добрый день. Скачал архив, распаковал в корень D, установил четыре аддона для питона из описания, стартую run_BTC,bat, базу подкинул в папку BF/btc.bf

D:\HtM-Lite-main>python -B PulsarLite.py -b BTC -dbbtc BF\btc.bf -th 3 -sl 5
Traceback (most recent call last):
  File "D:\HtM-Lite-main\PulsarLite.py", line 8, in <module>
    from funcP import *
  File "D:\HtM-Lite-main\funcP.py", line 7, in <module>
    from consts import *
  File "D:\HtM-Lite-main\consts.py", line 32, in <module>
    handler_found = logging.FileHandler(path.join(current_path+'/log', 'found.log'), 'a' , encoding ='utf-8')
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\HtM-Lite-main\\log\\found.log'

D:\HtM-Lite-main>pause
Для продолжения нажмите любую клавишу . . .

**Comment by Noname400** [comment]
в корне создайте папку log

**Comment by DFKTYNBY967** [comment]
папку log  создал.Фалы bf в папке  BF-create  сделал.Ввожу команду  python -B PulsarLite.py -b BTC -dbbtc BF\btc.bf -th 3 -sl 5 .Результат на скринах.Что не так плиз?
![CMD](https://user-images.githubusercontent.com/68655916/176929871-f159b2ca-ebdd-425e-8b16-dd4c15d0d424.jpg)
![PowerShell](https://user-images.githubusercontent.com/68655916/176929900-07ab2520-6937-4065-b2d9-bdc279be2a7e.jpg)
![команда для старта](https://user-images.githubusercontent.com/68655916/176929909-0de97546-3483-4aa0-a6c0-28f74d8b0855.jpg)
![ПАПКА  ЗАПУСКА ПРОГАММЫ](https://user-images.githubusercontent.com/68655916/176929923-eda203d6-5dbe-43b9-93d1-f7c3f630299a.jpg)
![папка BF](https://user-images.githubusercontent.com/68655916/176929928-24d3725d-f9fa-4013-be03-7bff779d66fc.jpg)
![файлы  bf ](https://user-images.githubusercontent.com/68655916/176929949-75a2ab8c-7290-4a60-9f1e-affbddafcf7e.jpg)

**Comment by DFKTYNBY967** [comment]
Система win-10-64

**Comment by Noname400** [comment]
у вас нет парки BF

**Comment by DFKTYNBY967** [comment]
![Скриншот 02-07-2022 111734](https://user-images.githubusercontent.com/68655916/176992758-ba6418e4-c995-4294-a9a6-6bec6870088b.jpg)




СПАСИБО ЗАРАБОТАЛА!!!
