### ISSUE TITLE
папку log  создал.Фалы bf в папке  BF-create  сделал.Ввожу команду  python -B PulsarLite.py -b BTC -dbbtc BF\btc.bf -th 3 -sl 5 .Результат на скринах.Что не так плиз?

### ISSUE THREAD

**Issue by DFKTYNBY967** [Noname400/HtM-Lite#5]
папку log  создал.Фалы bf в папке  BF-create  сделал.Ввожу команду  python -B PulsarLite.py -b BTC -dbbtc BF\btc.bf -th 3 -sl 5 .Результат на скринах.Что не так плиз?

![CMD](https://user-images.githubusercontent.com/68655916/176929871-f159b2ca-ebdd-425e-8b16-dd4c15d0d424.jpg)
![PowerShell](https://user-images.githubusercontent.com/68655916/176929900-07ab2520-6937-4065-b2d9-bdc279be2a7e.jpg)
![команда для старта](https://user-images.githubusercontent.com/68655916/176929909-0de97546-3483-4aa0-a6c0-28f74d8b0855.jpg)
![ПАПКА  ЗАПУСКА ПРОГАММЫ](https://user-images.githubusercontent.com/68655916/176929923-eda203d6-5dbe-43b9-93d1-f7c3f630299a.jpg)
![папка BF](https://user-images.githubusercontent.com/68655916/176929928-24d3725d-f9fa-4013-be03-7bff779d66fc.jpg)
![файлы  bf ](https://user-images.githubusercontent.com/68655916/176929949-75a2ab8c-7290-4a60-9f1e-affbddafcf7e.jpg)

_Originally posted by @DFKTYNBY967 in https://github.com/Noname400/HtM-Lite/issues/4#issuecomment-1172489810_

**Comment by Noname400** [comment]
![image](https://user-images.githubusercontent.com/74019756/176932910-392bd5c2-0d39-40cb-90a4-91a908fd8304.png)
![image](https://user-images.githubusercontent.com/74019756/176932910-392bd5c2-0d39-40cb-90a4-91a908fd8304.png)

**Comment by DFKTYNBY967** [comment]
Еще один вопрос? Адрес эфира  для блюм фильтра должен быть без 0x ?

**Comment by Noname400** [comment]
при создание блюм фильтра ?
без разницы. он различает их и создает правильные фильтры

**Comment by DFKTYNBY967** [comment]
Спасибо!
