### ISSUE TITLE
mmh3

### ISSUE THREAD

**Issue by Raipx** [Noname400/HtM-Lite#6]
Устанавливаю mmh3 через cmd (pip install mmh3) пробовал (python -m pip install mmh3) все MVS2005-2019+Build Tools установлены.
В чём может быть причина? Спасибо.
![image](https://user-images.githubusercontent.com/109918873/180660412-f6bc2259-1c9d-4305-8ffc-9f5dc5433098.png)

**Comment by Raipx** [comment]
проблема решена переустановкой Phyton на более старую версию.

**Comment by Noname400** [comment]
рекомендуемая версия 3,9
для установки mmh3 
можно использовать установку готовой библиотеки 
https://pypi.org/project/mmh3/#files
pip install mmh3-3.0.0-cp39-cp39-win_amd64.whl
